/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as HostingRouteImport } from './routes/hosting'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as PortalWalletRouteImport } from './routes/portal.wallet'
import { Route as PortalVpsRouteImport } from './routes/portal.vps'
import { Route as PortalTicketsRouteImport } from './routes/portal.tickets'
import { Route as PortalSubscriptionsRouteImport } from './routes/portal.subscriptions'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalOrdersRouteImport } from './routes/portal.orders'
import { Route as PortalMembershipRouteImport } from './routes/portal.membership'
import { Route as PortalLicensesRouteImport } from './routes/portal.licenses'
import { Route as PortalDownloadsRouteImport } from './routes/portal.downloads'
import { Route as PortalCoursesRouteImport } from './routes/portal.courses'
import { Route as PortalAffiliateRouteImport } from './routes/portal.affiliate'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as CertificatesVerifyRouteImport } from './routes/certificates.verify'
import { Route as AdminWhatsappOrdersRouteImport } from './routes/admin.whatsapp-orders'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as AdminWalletsRouteImport } from './routes/admin.wallets'
import { Route as AdminVpsRouteImport } from './routes/admin.vps'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminTicketWorkflowsRouteImport } from './routes/admin.ticket-workflows'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSslRouteImport } from './routes/admin.ssl'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminServersRouteImport } from './routes/admin.servers'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPwaRouteImport } from './routes/admin.pwa'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMonitoringRouteImport } from './routes/admin.monitoring'
import { Route as AdminMembershipsRouteImport } from './routes/admin.memberships'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminLicensesRouteImport } from './routes/admin.licenses'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminInfrastructureReportsRouteImport } from './routes/admin.infrastructure-reports'
import { Route as AdminHostingRouteImport } from './routes/admin.hosting'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminDomainsRouteImport } from './routes/admin.domains'
import { Route as AdminDigitalProductsRouteImport } from './routes/admin.digital-products'
import { Route as AdminCrmRouteImport } from './routes/admin.crm'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminContactSubmissionsRouteImport } from './routes/admin.contact-submissions'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBackupRouteImport } from './routes/admin.backup'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAmcRouteImport } from './routes/admin.amc'
import { Route as AdminAffiliatesRouteImport } from './routes/admin.affiliates'
import { Route as AdminAffiliateTemplatesRouteImport } from './routes/admin.affiliate-templates'
import { Route as AdminAffiliateRulesRouteImport } from './routes/admin.affiliate-rules'
import { Route as AdminAffiliateApplicationsRouteImport } from './routes/admin.affiliate-applications'
import { Route as PortalTicketsIndexRouteImport } from './routes/portal.tickets.index'
import { Route as CoursesSlugIndexRouteImport } from './routes/courses.$slug.index'
import { Route as AdminTicketsIndexRouteImport } from './routes/admin.tickets.index'
import { Route as AdminMembershipsIndexRouteImport } from './routes/admin.memberships.index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin.courses.index'
import { Route as PortalTicketsIdRouteImport } from './routes/portal.tickets.$id'
import { Route as CoursesSlugLearnRouteImport } from './routes/courses.$slug.learn'
import { Route as AdminTicketsIdRouteImport } from './routes/admin.tickets.$id'
import { Route as AdminMembershipsUsersRouteImport } from './routes/admin.memberships.users'
import { Route as AdminCoursesIdRouteImport } from './routes/admin.courses.$id'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const HostingRoute = HostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const PortalWalletRoute = PortalWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVpsRoute = PortalVpsRouteImport.update({
  id: '/vps',
  path: '/vps',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTicketsRoute = PortalTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSubscriptionsRoute = PortalSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOrdersRoute = PortalOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMembershipRoute = PortalMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLicensesRoute = PortalLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDownloadsRoute = PortalDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCoursesRoute = PortalCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAffiliateRoute = PortalAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => PortalRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const CertificatesVerifyRoute = CertificatesVerifyRouteImport.update({
  id: '/certificates/verify',
  path: '/certificates/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhatsappOrdersRoute = AdminWhatsappOrdersRouteImport.update({
  id: '/admin/whatsapp-orders',
  path: '/admin/whatsapp-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/admin/whatsapp',
  path: '/admin/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/admin/wallets',
  path: '/admin/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVpsRoute = AdminVpsRouteImport.update({
  id: '/admin/vps',
  path: '/admin/vps',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/admin/tickets',
  path: '/admin/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketWorkflowsRoute = AdminTicketWorkflowsRouteImport.update({
  id: '/admin/ticket-workflows',
  path: '/admin/ticket-workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSslRoute = AdminSslRouteImport.update({
  id: '/admin/ssl',
  path: '/admin/ssl',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServersRoute = AdminServersRouteImport.update({
  id: '/admin/servers',
  path: '/admin/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPwaRoute = AdminPwaRouteImport.update({
  id: '/admin/pwa',
  path: '/admin/pwa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/admin/monitoring',
  path: '/admin/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembershipsRoute = AdminMembershipsRouteImport.update({
  id: '/admin/memberships',
  path: '/admin/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/admin/marketing',
  path: '/admin/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLicensesRoute = AdminLicensesRouteImport.update({
  id: '/admin/licenses',
  path: '/admin/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/admin/invoices',
  path: '/admin/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInfrastructureReportsRoute =
  AdminInfrastructureReportsRouteImport.update({
    id: '/admin/infrastructure-reports',
    path: '/admin/infrastructure-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminHostingRoute = AdminHostingRouteImport.update({
  id: '/admin/hosting',
  path: '/admin/hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDomainsRoute = AdminDomainsRouteImport.update({
  id: '/admin/domains',
  path: '/admin/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDigitalProductsRoute = AdminDigitalProductsRouteImport.update({
  id: '/admin/digital-products',
  path: '/admin/digital-products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/admin/crm',
  path: '/admin/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactSubmissionsRoute = AdminContactSubmissionsRouteImport.update({
  id: '/admin/contact-submissions',
  path: '/admin/contact-submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/admin/cms',
  path: '/admin/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/admin/backup',
  path: '/admin/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAmcRoute = AdminAmcRouteImport.update({
  id: '/admin/amc',
  path: '/admin/amc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAffiliatesRoute = AdminAffiliatesRouteImport.update({
  id: '/admin/affiliates',
  path: '/admin/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAffiliateTemplatesRoute = AdminAffiliateTemplatesRouteImport.update({
  id: '/admin/affiliate-templates',
  path: '/admin/affiliate-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAffiliateRulesRoute = AdminAffiliateRulesRouteImport.update({
  id: '/admin/affiliate-rules',
  path: '/admin/affiliate-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAffiliateApplicationsRoute =
  AdminAffiliateApplicationsRouteImport.update({
    id: '/admin/affiliate-applications',
    path: '/admin/affiliate-applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalTicketsIndexRoute = PortalTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalTicketsRoute,
} as any)
const CoursesSlugIndexRoute = CoursesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesSlugRoute,
} as any)
const AdminTicketsIndexRoute = AdminTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTicketsRoute,
} as any)
const AdminMembershipsIndexRoute = AdminMembershipsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMembershipsRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const PortalTicketsIdRoute = PortalTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalTicketsRoute,
} as any)
const CoursesSlugLearnRoute = CoursesSlugLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => CoursesSlugRoute,
} as any)
const AdminTicketsIdRoute = AdminTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTicketsRoute,
} as any)
const AdminMembershipsUsersRoute = AdminMembershipsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminMembershipsRoute,
} as any)
const AdminCoursesIdRoute = AdminCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/deployments': typeof DeploymentsRoute
  '/hosting': typeof HostingRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/workflows': typeof WorkflowsRoute
  '/admin/affiliate-applications': typeof AdminAffiliateApplicationsRoute
  '/admin/affiliate-rules': typeof AdminAffiliateRulesRoute
  '/admin/affiliate-templates': typeof AdminAffiliateTemplatesRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/amc': typeof AdminAmcRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/contact-submissions': typeof AdminContactSubmissionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/crm': typeof AdminCrmRoute
  '/admin/digital-products': typeof AdminDigitalProductsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/hosting': typeof AdminHostingRoute
  '/admin/infrastructure-reports': typeof AdminInfrastructureReportsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/memberships': typeof AdminMembershipsRouteWithChildren
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/pwa': typeof AdminPwaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/servers': typeof AdminServersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/ssl': typeof AdminSslRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/ticket-workflows': typeof AdminTicketWorkflowsRoute
  '/admin/tickets': typeof AdminTicketsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/vps': typeof AdminVpsRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin/whatsapp-orders': typeof AdminWhatsappOrdersRoute
  '/certificates/verify': typeof CertificatesVerifyRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/portal/affiliate': typeof PortalAffiliateRoute
  '/portal/courses': typeof PortalCoursesRoute
  '/portal/downloads': typeof PortalDownloadsRoute
  '/portal/licenses': typeof PortalLicensesRoute
  '/portal/membership': typeof PortalMembershipRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/subscriptions': typeof PortalSubscriptionsRoute
  '/portal/tickets': typeof PortalTicketsRouteWithChildren
  '/portal/vps': typeof PortalVpsRoute
  '/portal/wallet': typeof PortalWalletRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/memberships/users': typeof AdminMembershipsUsersRoute
  '/admin/tickets/$id': typeof AdminTicketsIdRoute
  '/courses/$slug/learn': typeof CoursesSlugLearnRoute
  '/portal/tickets/$id': typeof PortalTicketsIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/memberships/': typeof AdminMembershipsIndexRoute
  '/admin/tickets/': typeof AdminTicketsIndexRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
  '/portal/tickets/': typeof PortalTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/deployments': typeof DeploymentsRoute
  '/hosting': typeof HostingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/workflows': typeof WorkflowsRoute
  '/admin/affiliate-applications': typeof AdminAffiliateApplicationsRoute
  '/admin/affiliate-rules': typeof AdminAffiliateRulesRoute
  '/admin/affiliate-templates': typeof AdminAffiliateTemplatesRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/amc': typeof AdminAmcRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/contact-submissions': typeof AdminContactSubmissionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/digital-products': typeof AdminDigitalProductsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/hosting': typeof AdminHostingRoute
  '/admin/infrastructure-reports': typeof AdminInfrastructureReportsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/pwa': typeof AdminPwaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/servers': typeof AdminServersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/ssl': typeof AdminSslRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/ticket-workflows': typeof AdminTicketWorkflowsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vps': typeof AdminVpsRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin/whatsapp-orders': typeof AdminWhatsappOrdersRoute
  '/certificates/verify': typeof CertificatesVerifyRoute
  '/p/$slug': typeof PSlugRoute
  '/portal/affiliate': typeof PortalAffiliateRoute
  '/portal/courses': typeof PortalCoursesRoute
  '/portal/downloads': typeof PortalDownloadsRoute
  '/portal/licenses': typeof PortalLicensesRoute
  '/portal/membership': typeof PortalMembershipRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/subscriptions': typeof PortalSubscriptionsRoute
  '/portal/vps': typeof PortalVpsRoute
  '/portal/wallet': typeof PortalWalletRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/portal': typeof PortalIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/memberships/users': typeof AdminMembershipsUsersRoute
  '/admin/tickets/$id': typeof AdminTicketsIdRoute
  '/courses/$slug/learn': typeof CoursesSlugLearnRoute
  '/portal/tickets/$id': typeof PortalTicketsIdRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/memberships': typeof AdminMembershipsIndexRoute
  '/admin/tickets': typeof AdminTicketsIndexRoute
  '/courses/$slug': typeof CoursesSlugIndexRoute
  '/portal/tickets': typeof PortalTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/deployments': typeof DeploymentsRoute
  '/hosting': typeof HostingRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/workflows': typeof WorkflowsRoute
  '/admin/affiliate-applications': typeof AdminAffiliateApplicationsRoute
  '/admin/affiliate-rules': typeof AdminAffiliateRulesRoute
  '/admin/affiliate-templates': typeof AdminAffiliateTemplatesRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/amc': typeof AdminAmcRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/contact-submissions': typeof AdminContactSubmissionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/crm': typeof AdminCrmRoute
  '/admin/digital-products': typeof AdminDigitalProductsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/hosting': typeof AdminHostingRoute
  '/admin/infrastructure-reports': typeof AdminInfrastructureReportsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/memberships': typeof AdminMembershipsRouteWithChildren
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/pwa': typeof AdminPwaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/servers': typeof AdminServersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/ssl': typeof AdminSslRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/ticket-workflows': typeof AdminTicketWorkflowsRoute
  '/admin/tickets': typeof AdminTicketsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/vps': typeof AdminVpsRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin/whatsapp-orders': typeof AdminWhatsappOrdersRoute
  '/certificates/verify': typeof CertificatesVerifyRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/portal/affiliate': typeof PortalAffiliateRoute
  '/portal/courses': typeof PortalCoursesRoute
  '/portal/downloads': typeof PortalDownloadsRoute
  '/portal/licenses': typeof PortalLicensesRoute
  '/portal/membership': typeof PortalMembershipRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/subscriptions': typeof PortalSubscriptionsRoute
  '/portal/tickets': typeof PortalTicketsRouteWithChildren
  '/portal/vps': typeof PortalVpsRoute
  '/portal/wallet': typeof PortalWalletRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/memberships/users': typeof AdminMembershipsUsersRoute
  '/admin/tickets/$id': typeof AdminTicketsIdRoute
  '/courses/$slug/learn': typeof CoursesSlugLearnRoute
  '/portal/tickets/$id': typeof PortalTicketsIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/memberships/': typeof AdminMembershipsIndexRoute
  '/admin/tickets/': typeof AdminTicketsIndexRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
  '/portal/tickets/': typeof PortalTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/deployments'
    | '/hosting'
    | '/portal'
    | '/pricing'
    | '/products'
    | '/reset-password'
    | '/services'
    | '/workflows'
    | '/admin/affiliate-applications'
    | '/admin/affiliate-rules'
    | '/admin/affiliate-templates'
    | '/admin/affiliates'
    | '/admin/amc'
    | '/admin/audit-logs'
    | '/admin/backup'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/contact-submissions'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/crm'
    | '/admin/digital-products'
    | '/admin/domains'
    | '/admin/employees'
    | '/admin/hosting'
    | '/admin/infrastructure-reports'
    | '/admin/invoices'
    | '/admin/licenses'
    | '/admin/marketing'
    | '/admin/memberships'
    | '/admin/monitoring'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/pwa'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/servers'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/ssl'
    | '/admin/subscriptions'
    | '/admin/ticket-workflows'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/vps'
    | '/admin/wallets'
    | '/admin/whatsapp'
    | '/admin/whatsapp-orders'
    | '/certificates/verify'
    | '/courses/$slug'
    | '/p/$slug'
    | '/portal/affiliate'
    | '/portal/courses'
    | '/portal/downloads'
    | '/portal/licenses'
    | '/portal/membership'
    | '/portal/orders'
    | '/portal/profile'
    | '/portal/subscriptions'
    | '/portal/tickets'
    | '/portal/vps'
    | '/portal/wallet'
    | '/products/$slug'
    | '/admin/'
    | '/courses/'
    | '/portal/'
    | '/products/'
    | '/admin/courses/$id'
    | '/admin/memberships/users'
    | '/admin/tickets/$id'
    | '/courses/$slug/learn'
    | '/portal/tickets/$id'
    | '/admin/courses/'
    | '/admin/memberships/'
    | '/admin/tickets/'
    | '/courses/$slug/'
    | '/portal/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/deployments'
    | '/hosting'
    | '/pricing'
    | '/reset-password'
    | '/services'
    | '/workflows'
    | '/admin/affiliate-applications'
    | '/admin/affiliate-rules'
    | '/admin/affiliate-templates'
    | '/admin/affiliates'
    | '/admin/amc'
    | '/admin/audit-logs'
    | '/admin/backup'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/contact-submissions'
    | '/admin/coupons'
    | '/admin/crm'
    | '/admin/digital-products'
    | '/admin/domains'
    | '/admin/employees'
    | '/admin/hosting'
    | '/admin/infrastructure-reports'
    | '/admin/invoices'
    | '/admin/licenses'
    | '/admin/marketing'
    | '/admin/monitoring'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/pwa'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/servers'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/ssl'
    | '/admin/subscriptions'
    | '/admin/ticket-workflows'
    | '/admin/users'
    | '/admin/vps'
    | '/admin/wallets'
    | '/admin/whatsapp'
    | '/admin/whatsapp-orders'
    | '/certificates/verify'
    | '/p/$slug'
    | '/portal/affiliate'
    | '/portal/courses'
    | '/portal/downloads'
    | '/portal/licenses'
    | '/portal/membership'
    | '/portal/orders'
    | '/portal/profile'
    | '/portal/subscriptions'
    | '/portal/vps'
    | '/portal/wallet'
    | '/products/$slug'
    | '/admin'
    | '/courses'
    | '/portal'
    | '/products'
    | '/admin/courses/$id'
    | '/admin/memberships/users'
    | '/admin/tickets/$id'
    | '/courses/$slug/learn'
    | '/portal/tickets/$id'
    | '/admin/courses'
    | '/admin/memberships'
    | '/admin/tickets'
    | '/courses/$slug'
    | '/portal/tickets'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/deployments'
    | '/hosting'
    | '/portal'
    | '/pricing'
    | '/products'
    | '/reset-password'
    | '/services'
    | '/workflows'
    | '/admin/affiliate-applications'
    | '/admin/affiliate-rules'
    | '/admin/affiliate-templates'
    | '/admin/affiliates'
    | '/admin/amc'
    | '/admin/audit-logs'
    | '/admin/backup'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/contact-submissions'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/crm'
    | '/admin/digital-products'
    | '/admin/domains'
    | '/admin/employees'
    | '/admin/hosting'
    | '/admin/infrastructure-reports'
    | '/admin/invoices'
    | '/admin/licenses'
    | '/admin/marketing'
    | '/admin/memberships'
    | '/admin/monitoring'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/pwa'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/servers'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/ssl'
    | '/admin/subscriptions'
    | '/admin/ticket-workflows'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/vps'
    | '/admin/wallets'
    | '/admin/whatsapp'
    | '/admin/whatsapp-orders'
    | '/certificates/verify'
    | '/courses/$slug'
    | '/p/$slug'
    | '/portal/affiliate'
    | '/portal/courses'
    | '/portal/downloads'
    | '/portal/licenses'
    | '/portal/membership'
    | '/portal/orders'
    | '/portal/profile'
    | '/portal/subscriptions'
    | '/portal/tickets'
    | '/portal/vps'
    | '/portal/wallet'
    | '/products/$slug'
    | '/admin/'
    | '/courses/'
    | '/portal/'
    | '/products/'
    | '/admin/courses/$id'
    | '/admin/memberships/users'
    | '/admin/tickets/$id'
    | '/courses/$slug/learn'
    | '/portal/tickets/$id'
    | '/admin/courses/'
    | '/admin/memberships/'
    | '/admin/tickets/'
    | '/courses/$slug/'
    | '/portal/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DeploymentsRoute: typeof DeploymentsRoute
  HostingRoute: typeof HostingRoute
  PortalRoute: typeof PortalRouteWithChildren
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  WorkflowsRoute: typeof WorkflowsRoute
  AdminAffiliateApplicationsRoute: typeof AdminAffiliateApplicationsRoute
  AdminAffiliateRulesRoute: typeof AdminAffiliateRulesRoute
  AdminAffiliateTemplatesRoute: typeof AdminAffiliateTemplatesRoute
  AdminAffiliatesRoute: typeof AdminAffiliatesRoute
  AdminAmcRoute: typeof AdminAmcRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBackupRoute: typeof AdminBackupRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminContactSubmissionsRoute: typeof AdminContactSubmissionsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCoursesRoute: typeof AdminCoursesRouteWithChildren
  AdminCrmRoute: typeof AdminCrmRoute
  AdminDigitalProductsRoute: typeof AdminDigitalProductsRoute
  AdminDomainsRoute: typeof AdminDomainsRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminHostingRoute: typeof AdminHostingRoute
  AdminInfrastructureReportsRoute: typeof AdminInfrastructureReportsRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminLicensesRoute: typeof AdminLicensesRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminMembershipsRoute: typeof AdminMembershipsRouteWithChildren
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPwaRoute: typeof AdminPwaRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminServersRoute: typeof AdminServersRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSslRoute: typeof AdminSslRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTicketWorkflowsRoute: typeof AdminTicketWorkflowsRoute
  AdminTicketsRoute: typeof AdminTicketsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVpsRoute: typeof AdminVpsRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminWhatsappOrdersRoute: typeof AdminWhatsappOrdersRoute
  CertificatesVerifyRoute: typeof CertificatesVerifyRoute
  PSlugRoute: typeof PSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosting': {
      id: '/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof HostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/portal/wallet': {
      id: '/portal/wallet'
      path: '/wallet'
      fullPath: '/portal/wallet'
      preLoaderRoute: typeof PortalWalletRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/vps': {
      id: '/portal/vps'
      path: '/vps'
      fullPath: '/portal/vps'
      preLoaderRoute: typeof PortalVpsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tickets': {
      id: '/portal/tickets'
      path: '/tickets'
      fullPath: '/portal/tickets'
      preLoaderRoute: typeof PortalTicketsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/subscriptions': {
      id: '/portal/subscriptions'
      path: '/subscriptions'
      fullPath: '/portal/subscriptions'
      preLoaderRoute: typeof PortalSubscriptionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/orders': {
      id: '/portal/orders'
      path: '/orders'
      fullPath: '/portal/orders'
      preLoaderRoute: typeof PortalOrdersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/membership': {
      id: '/portal/membership'
      path: '/membership'
      fullPath: '/portal/membership'
      preLoaderRoute: typeof PortalMembershipRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/licenses': {
      id: '/portal/licenses'
      path: '/licenses'
      fullPath: '/portal/licenses'
      preLoaderRoute: typeof PortalLicensesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/downloads': {
      id: '/portal/downloads'
      path: '/downloads'
      fullPath: '/portal/downloads'
      preLoaderRoute: typeof PortalDownloadsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/courses': {
      id: '/portal/courses'
      path: '/courses'
      fullPath: '/portal/courses'
      preLoaderRoute: typeof PortalCoursesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/affiliate': {
      id: '/portal/affiliate'
      path: '/affiliate'
      fullPath: '/portal/affiliate'
      preLoaderRoute: typeof PortalAffiliateRouteImport
      parentRoute: typeof PortalRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/certificates/verify': {
      id: '/certificates/verify'
      path: '/certificates/verify'
      fullPath: '/certificates/verify'
      preLoaderRoute: typeof CertificatesVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whatsapp-orders': {
      id: '/admin/whatsapp-orders'
      path: '/admin/whatsapp-orders'
      fullPath: '/admin/whatsapp-orders'
      preLoaderRoute: typeof AdminWhatsappOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/admin/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/admin/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vps': {
      id: '/admin/vps'
      path: '/admin/vps'
      fullPath: '/admin/vps'
      preLoaderRoute: typeof AdminVpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ticket-workflows': {
      id: '/admin/ticket-workflows'
      path: '/admin/ticket-workflows'
      fullPath: '/admin/ticket-workflows'
      preLoaderRoute: typeof AdminTicketWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ssl': {
      id: '/admin/ssl'
      path: '/admin/ssl'
      fullPath: '/admin/ssl'
      preLoaderRoute: typeof AdminSslRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/servers': {
      id: '/admin/servers'
      path: '/admin/servers'
      fullPath: '/admin/servers'
      preLoaderRoute: typeof AdminServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pwa': {
      id: '/admin/pwa'
      path: '/admin/pwa'
      fullPath: '/admin/pwa'
      preLoaderRoute: typeof AdminPwaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/memberships': {
      id: '/admin/memberships'
      path: '/admin/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AdminMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/admin/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/licenses': {
      id: '/admin/licenses'
      path: '/admin/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AdminLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/admin/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/infrastructure-reports': {
      id: '/admin/infrastructure-reports'
      path: '/admin/infrastructure-reports'
      fullPath: '/admin/infrastructure-reports'
      preLoaderRoute: typeof AdminInfrastructureReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hosting': {
      id: '/admin/hosting'
      path: '/admin/hosting'
      fullPath: '/admin/hosting'
      preLoaderRoute: typeof AdminHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/domains': {
      id: '/admin/domains'
      path: '/admin/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AdminDomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/digital-products': {
      id: '/admin/digital-products'
      path: '/admin/digital-products'
      fullPath: '/admin/digital-products'
      preLoaderRoute: typeof AdminDigitalProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contact-submissions': {
      id: '/admin/contact-submissions'
      path: '/admin/contact-submissions'
      fullPath: '/admin/contact-submissions'
      preLoaderRoute: typeof AdminContactSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/admin/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/admin/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/amc': {
      id: '/admin/amc'
      path: '/admin/amc'
      fullPath: '/admin/amc'
      preLoaderRoute: typeof AdminAmcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/affiliates': {
      id: '/admin/affiliates'
      path: '/admin/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AdminAffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/affiliate-templates': {
      id: '/admin/affiliate-templates'
      path: '/admin/affiliate-templates'
      fullPath: '/admin/affiliate-templates'
      preLoaderRoute: typeof AdminAffiliateTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/affiliate-rules': {
      id: '/admin/affiliate-rules'
      path: '/admin/affiliate-rules'
      fullPath: '/admin/affiliate-rules'
      preLoaderRoute: typeof AdminAffiliateRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/affiliate-applications': {
      id: '/admin/affiliate-applications'
      path: '/admin/affiliate-applications'
      fullPath: '/admin/affiliate-applications'
      preLoaderRoute: typeof AdminAffiliateApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/tickets/': {
      id: '/portal/tickets/'
      path: '/'
      fullPath: '/portal/tickets/'
      preLoaderRoute: typeof PortalTicketsIndexRouteImport
      parentRoute: typeof PortalTicketsRoute
    }
    '/courses/$slug/': {
      id: '/courses/$slug/'
      path: '/'
      fullPath: '/courses/$slug/'
      preLoaderRoute: typeof CoursesSlugIndexRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
    '/admin/tickets/': {
      id: '/admin/tickets/'
      path: '/'
      fullPath: '/admin/tickets/'
      preLoaderRoute: typeof AdminTicketsIndexRouteImport
      parentRoute: typeof AdminTicketsRoute
    }
    '/admin/memberships/': {
      id: '/admin/memberships/'
      path: '/'
      fullPath: '/admin/memberships/'
      preLoaderRoute: typeof AdminMembershipsIndexRouteImport
      parentRoute: typeof AdminMembershipsRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/portal/tickets/$id': {
      id: '/portal/tickets/$id'
      path: '/$id'
      fullPath: '/portal/tickets/$id'
      preLoaderRoute: typeof PortalTicketsIdRouteImport
      parentRoute: typeof PortalTicketsRoute
    }
    '/courses/$slug/learn': {
      id: '/courses/$slug/learn'
      path: '/learn'
      fullPath: '/courses/$slug/learn'
      preLoaderRoute: typeof CoursesSlugLearnRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
    '/admin/tickets/$id': {
      id: '/admin/tickets/$id'
      path: '/$id'
      fullPath: '/admin/tickets/$id'
      preLoaderRoute: typeof AdminTicketsIdRouteImport
      parentRoute: typeof AdminTicketsRoute
    }
    '/admin/memberships/users': {
      id: '/admin/memberships/users'
      path: '/users'
      fullPath: '/admin/memberships/users'
      preLoaderRoute: typeof AdminMembershipsUsersRouteImport
      parentRoute: typeof AdminMembershipsRoute
    }
    '/admin/courses/$id': {
      id: '/admin/courses/$id'
      path: '/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AdminCoursesIdRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
  }
}

interface CoursesSlugRouteChildren {
  CoursesSlugLearnRoute: typeof CoursesSlugLearnRoute
  CoursesSlugIndexRoute: typeof CoursesSlugIndexRoute
}

const CoursesSlugRouteChildren: CoursesSlugRouteChildren = {
  CoursesSlugLearnRoute: CoursesSlugLearnRoute,
  CoursesSlugIndexRoute: CoursesSlugIndexRoute,
}

const CoursesSlugRouteWithChildren = CoursesSlugRoute._addFileChildren(
  CoursesSlugRouteChildren,
)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRouteWithChildren
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRouteWithChildren,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface PortalTicketsRouteChildren {
  PortalTicketsIdRoute: typeof PortalTicketsIdRoute
  PortalTicketsIndexRoute: typeof PortalTicketsIndexRoute
}

const PortalTicketsRouteChildren: PortalTicketsRouteChildren = {
  PortalTicketsIdRoute: PortalTicketsIdRoute,
  PortalTicketsIndexRoute: PortalTicketsIndexRoute,
}

const PortalTicketsRouteWithChildren = PortalTicketsRoute._addFileChildren(
  PortalTicketsRouteChildren,
)

interface PortalRouteChildren {
  PortalAffiliateRoute: typeof PortalAffiliateRoute
  PortalCoursesRoute: typeof PortalCoursesRoute
  PortalDownloadsRoute: typeof PortalDownloadsRoute
  PortalLicensesRoute: typeof PortalLicensesRoute
  PortalMembershipRoute: typeof PortalMembershipRoute
  PortalOrdersRoute: typeof PortalOrdersRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalSubscriptionsRoute: typeof PortalSubscriptionsRoute
  PortalTicketsRoute: typeof PortalTicketsRouteWithChildren
  PortalVpsRoute: typeof PortalVpsRoute
  PortalWalletRoute: typeof PortalWalletRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAffiliateRoute: PortalAffiliateRoute,
  PortalCoursesRoute: PortalCoursesRoute,
  PortalDownloadsRoute: PortalDownloadsRoute,
  PortalLicensesRoute: PortalLicensesRoute,
  PortalMembershipRoute: PortalMembershipRoute,
  PortalOrdersRoute: PortalOrdersRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalSubscriptionsRoute: PortalSubscriptionsRoute,
  PortalTicketsRoute: PortalTicketsRouteWithChildren,
  PortalVpsRoute: PortalVpsRoute,
  PortalWalletRoute: PortalWalletRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface AdminCoursesRouteChildren {
  AdminCoursesIdRoute: typeof AdminCoursesIdRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
}

const AdminCoursesRouteChildren: AdminCoursesRouteChildren = {
  AdminCoursesIdRoute: AdminCoursesIdRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
}

const AdminCoursesRouteWithChildren = AdminCoursesRoute._addFileChildren(
  AdminCoursesRouteChildren,
)

interface AdminMembershipsRouteChildren {
  AdminMembershipsUsersRoute: typeof AdminMembershipsUsersRoute
  AdminMembershipsIndexRoute: typeof AdminMembershipsIndexRoute
}

const AdminMembershipsRouteChildren: AdminMembershipsRouteChildren = {
  AdminMembershipsUsersRoute: AdminMembershipsUsersRoute,
  AdminMembershipsIndexRoute: AdminMembershipsIndexRoute,
}

const AdminMembershipsRouteWithChildren =
  AdminMembershipsRoute._addFileChildren(AdminMembershipsRouteChildren)

interface AdminTicketsRouteChildren {
  AdminTicketsIdRoute: typeof AdminTicketsIdRoute
  AdminTicketsIndexRoute: typeof AdminTicketsIndexRoute
}

const AdminTicketsRouteChildren: AdminTicketsRouteChildren = {
  AdminTicketsIdRoute: AdminTicketsIdRoute,
  AdminTicketsIndexRoute: AdminTicketsIndexRoute,
}

const AdminTicketsRouteWithChildren = AdminTicketsRoute._addFileChildren(
  AdminTicketsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DeploymentsRoute: DeploymentsRoute,
  HostingRoute: HostingRoute,
  PortalRoute: PortalRouteWithChildren,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  WorkflowsRoute: WorkflowsRoute,
  AdminAffiliateApplicationsRoute: AdminAffiliateApplicationsRoute,
  AdminAffiliateRulesRoute: AdminAffiliateRulesRoute,
  AdminAffiliateTemplatesRoute: AdminAffiliateTemplatesRoute,
  AdminAffiliatesRoute: AdminAffiliatesRoute,
  AdminAmcRoute: AdminAmcRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBackupRoute: AdminBackupRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminContactSubmissionsRoute: AdminContactSubmissionsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCoursesRoute: AdminCoursesRouteWithChildren,
  AdminCrmRoute: AdminCrmRoute,
  AdminDigitalProductsRoute: AdminDigitalProductsRoute,
  AdminDomainsRoute: AdminDomainsRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminHostingRoute: AdminHostingRoute,
  AdminInfrastructureReportsRoute: AdminInfrastructureReportsRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminLicensesRoute: AdminLicensesRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminMembershipsRoute: AdminMembershipsRouteWithChildren,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPwaRoute: AdminPwaRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminServersRoute: AdminServersRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSslRoute: AdminSslRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTicketWorkflowsRoute: AdminTicketWorkflowsRoute,
  AdminTicketsRoute: AdminTicketsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminVpsRoute: AdminVpsRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminWhatsappOrdersRoute: AdminWhatsappOrdersRoute,
  CertificatesVerifyRoute: CertificatesVerifyRoute,
  PSlugRoute: PSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
